/**
 * Writes `supabase/migrations/0003_locations.sql` from `src/data/locations.ts`,
 * so the server can check which outlets a promoter may be working at without
 * a second copy of the list drifting out of step.
 *
 *   npx vite-node scripts/locations-sql.ts
 *
 * Run it again whenever an outlet opens, closes or moves town, and re-run the
 * migration. Nothing here is a secret.
 */
import { writeFileSync } from 'node:fs'
import { locations } from '../src/data/locations'

const rows = locations.map((l) =>
  JSON.stringify({ id: l.id, name: l.name, channel: l.channel, city: l.city ?? null, status: l.status }),
)

writeFileSync(
  'supabase/migrations/0003_locations.sql',
  `-- Generated by scripts/locations-sql.ts from src/data/locations.ts. Do not edit by hand.
--
-- The outlets. The server uses the town on a main store to decide which of
-- them a promoter may pick at sign-in, so this has to match the app's own
-- list. Re-running replaces every row.

select seed_locations($$[
${rows.join(',\n')}
]$$::jsonb);
`,
)
console.log(`wrote ${locations.length} outlets`)
