/**
 * Writes `supabase/migrations/0002_people.sql` from the people list in
 * `src/data/people.ts`, so the server starts with exactly the logins the
 * client gave us. Every person gets a random password (see the migration);
 * nothing here is a secret.
 *
 *   npx vite-node scripts/people-sql.ts
 */
import { writeFileSync } from 'node:fs'
import { seedPeople } from '../src/data/people'

const sql = `-- Generated by scripts/people-sql.ts from src/data/people.ts. Do not edit by hand.
--
-- The thirty-nine logins from the client's list. Each is inserted with a
-- random password (see seed_people() in 0001_init.sql), which Imran reads off
-- the Logins screen and hands over. Re-running this is safe: people who
-- already exist are left alone, passwords included.

select seed_people($$[
${seedPeople.map((p) => JSON.stringify(p)).join(',\n')}
]$$::jsonb);
`
writeFileSync('supabase/migrations/0002_people.sql', sql)
console.log(`wrote ${seedPeople.length} people`)
