/**
 * Writes `supabase/migrations/0004_promoter_cities.sql`.
 *
 *   npx vite-node scripts/promoter-cities-sql.ts
 *
 * A one-time change of shape, for servers seeded before promoters belonged to
 * a town rather than to a single store. It moves each promoter onto their city
 * and clears the fixed store; everything else about the login — password,
 * whether it is active, any correction made on the Logins screen — is left
 * exactly as it is. Safe to run more than once.
 */
import { writeFileSync } from 'node:fs'
import { seedPeople, storeChoicesFor } from '../src/data/people'

const promoters = seedPeople.filter((p) => p.role === 'promoter')
const rows = promoters.map((p) =>
  JSON.stringify({ id: p.id, city: p.city, storeChoices: storeChoicesFor(p) }),
)

writeFileSync(
  'supabase/migrations/0004_promoter_cities.sql',
  `-- Generated by scripts/promoter-cities-sql.ts. Do not edit by hand.
--
-- Promoters used to be fixed to one store. Staff are rotated between the
-- counters in their own town, so each now belongs to a city and says which
-- outlet they are at when they sign in. This moves the logins already on the
-- server across. Passwords and everything else are untouched.

update people p
   set doc = (p.doc - 'locationId')
             || jsonb_build_object('city', c.city, 'storeChoices', c.choices),
       updated_at = now()
  from (
    select value->>'id' as id,
           value->>'city' as city,
           value->'storeChoices' as choices
      from jsonb_array_elements($$[
${rows.join(',\n')}
]$$::jsonb)
  ) c
 where p.id = c.id
   and (p.doc->>'city' is distinct from c.city or p.doc ? 'locationId');

select count(*)::int as promoters_on_a_town from people where doc ? 'city';
`,
)
console.log(`wrote ${promoters.length} promoters`)
