-- Generated by scripts/promoter-cities-sql.ts. Do not edit by hand.
--
-- Promoters used to be fixed to one store. Staff are rotated between the
-- counters in their own town, so each now belongs to a city and says which
-- outlet they are at when they sign in. This moves the logins already on the
-- server across. Passwords and everything else are untouched.

update people p
   set doc = (p.doc - 'locationId')
             || jsonb_build_object('city', c.city, 'storeChoices', c.choices),
       updated_at = now()
  from (
    select value->>'id' as id,
           value->>'city' as city,
           value->'storeChoices' as choices
      from jsonb_array_elements($$[
{"id":"teokoknian","city":"KLIA","storeChoices":["klia-t2"]},
{"id":"tanshimin","city":"KLIA","storeChoices":["klia-t2"]},
{"id":"yongsetyee","city":"KLIA","storeChoices":["klia-t2"]},
{"id":"sayzhengqiang","city":"KLIA","storeChoices":["klia-t2"]},
{"id":"gohmeeling","city":"KLIA","storeChoices":["klia-t2"]},
{"id":"chweehuining","city":"KLIA","storeChoices":["klia-t2"]},
{"id":"lookpohlei","city":"Langkawi","storeChoices":["langkawi"]},
{"id":"tangwinnie","city":"Langkawi","storeChoices":["langkawi"]},
{"id":"quahchuen","city":"Langkawi","storeChoices":["langkawi"]},
{"id":"engellahii","city":"Kota Kinabalu","storeChoices":["parkson-imago"]},
{"id":"siewziching","city":"Genting Highlands","storeChoices":["genting"]},
{"id":"ngmengxiang","city":"Genting Highlands","storeChoices":["genting"]},
{"id":"leekwansern","city":"Kuala Lumpur","storeChoices":["pavilion-5","bsas","parkson-pavilion","klcc-isetan"]},
{"id":"limzhixuan","city":"Kuala Lumpur","storeChoices":["pavilion-5","bsas","parkson-pavilion","klcc-isetan"]},
{"id":"tanjiwei","city":"Kuala Lumpur","storeChoices":["pavilion-5","bsas","parkson-pavilion","klcc-isetan"]},
{"id":"eddielee","city":"Kuala Lumpur","storeChoices":["pavilion-5","bsas","parkson-pavilion","klcc-isetan"]},
{"id":"limyongkent","city":"Kuala Lumpur","storeChoices":["pavilion-5","bsas","parkson-pavilion","klcc-isetan"]},
{"id":"shannesslow","city":"Kuala Lumpur","storeChoices":["pavilion-5","bsas","parkson-pavilion","klcc-isetan"]},
{"id":"fonghaobin","city":"Kuala Lumpur","storeChoices":["pavilion-5","bsas","parkson-pavilion","klcc-isetan"]},
{"id":"yapboonming","city":"Kuala Lumpur","storeChoices":["pavilion-5","bsas","parkson-pavilion","klcc-isetan"]},
{"id":"desmondchang","city":"Kuala Lumpur","storeChoices":["pavilion-5","bsas","parkson-pavilion","klcc-isetan"]},
{"id":"gohzixuan","city":"Kuala Lumpur","storeChoices":["pavilion-5","bsas","parkson-pavilion","klcc-isetan"]},
{"id":"chanqijun","city":"Kuala Lumpur","storeChoices":["pavilion-5","bsas","parkson-pavilion","klcc-isetan"]},
{"id":"danzeltan","city":"Kuala Lumpur","storeChoices":["pavilion-5","bsas","parkson-pavilion","klcc-isetan"]},
{"id":"khookwoktsu","city":"Melaka","storeChoices":["melaka"]},
{"id":"chewyingtian","city":"Melaka","storeChoices":["melaka"]},
{"id":"kokchewling","city":"Melaka","storeChoices":["melaka"]}
]$$::jsonb)
  ) c
 where p.id = c.id
   and (p.doc->>'city' is distinct from c.city or p.doc ? 'locationId');

select count(*)::int as promoters_on_a_town from people where doc ? 'city';
